import keyMirror from 'key-mirror'

export default keyMirror({

  SET_PLATFORM: null,
  SET_VERSION: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_START: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,
  LOGIN_SOCIAL: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  // LoginForm.js
  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  GET_ALL_TRIP: null,
  GET_ALL_TRIP_SUCCESS: null,
  GET_ALL_TRIP_FAILURE: null,
  GET_TRIP_BY_CLASS: null,

  SET_TRIP_KEY: null,

  GET_TRIP_CONTENT: null,
  GET_TRIP_CONTENT_SUCCESS: null,
  GET_TRIP_CONTENT_FAILURE: null,

  SET_SITE_CONTENT_SUCCESS: null,
  SET_SITE_CONTENT_FAILURE: null,

  SET_SITE_STATUS: null,

  SET_DISPLAY_INFO: null,
  CLOSE_DISPLAY_INFO: null,

  ACTIVATE_SITE_BTN: null,
  DEACTIVATE_SITE_BTN: null,

  SET_MAP_INFO: null,
  SET_MAP_INFO_SUCCESS: null,
  SET_MAP_INFO_FAILURE: null,
  SET_MAP_DIRECTION: null,
  SET_MAP_DIRECTION_ERROR: null,

  SET_AUDIO: null,
  RESET_AUDIO: null,

  SET_DISPLAY_INFO_TRANSIT: null,
  SET_DISPLAY_INFO_TRANSIT_SUCCESS: null,
  SET_DISPLAY_INFO_TRANSIT_FAILURE: null,
  TOGGLE_DISPLAY_INFO: null,

  TOGGLE_MAP_MODE: null,

  SWITCH_DISPLAY_INFO_CARD: null,

  PRESS_MARKER_FAILURE: null,
})
