export const dayData = [
  { key: 1, label: '一天' },
  { key: 2, label: '二天' },
  { key: 3, label: '三天' },
  { key: 4, label: '四天' },
  { key: 5, label: '五天' },
  { key: 6, label: '六天' },
  { key: 7, label: '七天' },
  { key: 8, label: '八天' },
  { key: 9, label: '九天' },
  { key: 10, label: '十天' },
]

export const hotelType = [
  { key: 0, label: '嚮導推薦' },
  { key: 1, label: '民宿' },
  { key: 2, label: '飯店' },
  { key: 3, label: '汽車旅館' },
  { key: 4, label: '膠囊旅館' },
]

export const tripLocation = [
  { key: 0, label: '嚮導推薦' },
  { key: 'northern', section: true, label: '北部' },
  { key: 1, label: '台北' },
  { key: 2, label: '基隆' },
  { key: 3, label: '新北' },
  { key: 4, label: '桃園' },
  { key: 5, label: '新竹' },
  { key: 'central', section: true, label: '中部' },
  { key: 6, label: '苗栗' },
  { key: 7, label: '台中' },
  { key: 8, label: '彰化' },
  { key: 9, label: '南投' },
  { key: 10, label: '雲林' },
  { key: 'southern', section: true, label: '南部' },
  { key: 11, label: '嘉義' },
  { key: 12, label: '台南' },
  { key: 13, label: '高雄' },
  { key: 14, label: '屏東' },
  { key: 'eastern', section: true, label: '東部' },
  { key: 15, label: '宜蘭' },
  { key: 16, label: '台東' },
  { key: 17, label: '花蓮' },
  { key: 'island', section: true, label: '離島' },
  { key: 18, label: '綠島' },
  { key: 19, label: '蘭嶼' },
  { key: 20, label: '金門' },
  { key: 21, label: '馬祖' },
  { key: 22, label: '澎湖' },
  { key: 23, label: '小琉球' },
]

export const tripElement = [
  { key: 0, label: '請導遊幫我推薦旅遊行程' },
  { key: 1, label: '海邊' },
  { key: 2, label: '山景' },
  { key: 3, label: '農場/莊園' },
  { key: 4, label: '動物互動' },
  { key: 5, label: '賞花賞楓' },
  { key: 6, label: '市場市集' },
  { key: 7, label: '浮淺/深淺' },
  { key: 8, label: '溯溪' },
  { key: 9, label: '獨木舟/泛舟' },
  { key: 10, label: '衝浪' },
  { key: 11, label: '當地特色文化' },
  { key: 12, label: '歷史建築及遺跡' },
  { key: 13, label: '美術和博物館' },
  { key: 14, label: '宗教巡禮' },
  { key: 15, label: '慶典' },
  { key: 16, label: '戲劇音樂表演' },
  { key: 17, label: '賽車/越野車' },
  { key: 18, label: '自行車' },
  { key: 19, label: '健走登山' },
  { key: 20, label: '生存遊戲' },
  { key: 21, label: '漆彈' },
  { key: 22, label: '高空彈跳' },
  { key: 23, label: '滑翔傘' },
  { key: 24, label: '攀岩' },
  { key: 25, label: '跳舞' },
  { key: 26, label: '喝酒' },
  { key: 27, label: '聊天' },
  { key: 28, label: '聽演唱' },
  { key: 29, label: '夜景-山景' },
  { key: 30, label: '夜景-海景' },
  { key: 31, label: '百貨公司' },
  { key: 32, label: '韓系' },
  { key: 33, label: '日系' },
  { key: 34, label: '美式休閒' },
  { key: 35, label: '地陪' },
]
export const tripAll = [
  {
    name: '觀光踏青',
    element: [1, 2, 3, 4, 5, 6],
  },
  {
    name: '水上活動',
    element: [7, 8, 9, 10],
  },
  {
    name: '文化藝術歷史音樂',
    element: [11, 12, 13, 14, 15, 16],
  },
  {
    name: '戶外運動',
    element: [17, 18, 19, 20, 21, 22, 23, 24],
  },
  {
    name: '夜生活',
    element: [25, 26, 27, 28, 29, 30],
  },
  {
    name: '逛街',
    element: [31, 32, 33, 34],
  },
  {
    name: '其它',
    element: [35],
  },
]

export const foodElement = [
  { key: 0, label: '隨意' },
  { key: 1, label: '日式' },
  { key: 2, label: '中式' },
  { key: 3, label: '港式' },
  { key: 4, label: '泰式' },
  { key: 5, label: '美式' },
  { key: 6, label: '西式' },
  { key: 7, label: '吃到飽' },
  { key: 8, label: '夜市' },
]
