const React = require('react-native')
const { StyleSheet } = React
module.exports = StyleSheet.create({
  Image: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 355,
    height: 130,
    backgroundColor: 'transparent',
    borderRadius: 10,
  },
  Title: {
    fontSize: 20,
    marginLeft: 20,
    marginTop: 15,
    color: 'white',
    width: 175,
    height: 25,
  },
  dayInfo: {
    marginTop: -15,
    marginLeft: 20,
    color: 'white',
    fontSize: 13,
    borderWidth: 1,
    borderColor: 'white',
    width: 50,
    height: 20,
    padding: 3,
  },
  star: {
    marginLeft: 22,
    marginTop: 30,
    width: 10,
    color: 'white',
  },
  starNumber: {
    marginLeft: 5,
    fontSize: 11,
    color: 'white',
    marginTop: 28,
  },
  guide: {
    marginLeft: 10,
    paddingLeft: 280,
    width: 355,
    height: 20,
    fontSize: 13,
    color: 'white',
  },
  watch: {
    marginLeft: 10,
    marginTop: 28,
    width: 10,
    color: 'white',
  },
  watchNumber: {
    marginLeft: 5,
    fontSize: 11,
    color: 'white',
    marginTop: 28,
  },
  shoppingCart: {
    marginLeft: 10,
    marginTop: 28,
    width: 10,
    color: 'white',
  },
  numOfPurchase: {
    marginLeft: 5,
    fontSize: 11,
    color: 'white',
    marginTop: 28,
  },
  cost: {
    marginTop: 13,
    fontSize: 25,
    color: 'white',
    marginLeft: 120,
  },
  unit: {
    marginTop: 21,
    fontSize: 15,
    color: 'white',
  },
  thumbnailImage: {
    marginTop: 10,
    marginLeft: 90,
    borderRadius: 25,
    borderColor: 'white',
    borderWidth: 1,
    height: 50,
    width: 50,
  },
})
